---
title: "Data Management Plan"
description: |
author:
  - name: Maddy Shanks 
    url: 
    affiliation: University of South Carolina
    affiliation_url: 
#date: "`r Sys.Date()`"
header-includes:
##- \usepackage{kotex}
#mainfont: mathpazo
#urlcolor: blue
output: 
  rmdformats::robobook:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

In the interest of open science, the public availability of scientific
data is of the upmost importance. The data generated by this research
will primarily be biographical and demographical information on the
attorneys participating in criminal cases before the federal district
courts, based on publicly available documents accessed via WestLaw Edge.
The observations are cases and, while case characteristics will be
included in the resulting dataset, the base dataset from the Integrated
Database (IDB) of Federal District Court Decisions contains no
identifying information on the defendants and no identifying information
on the defendants will be collected. Rather, all data collected will
pertain to the attorneys in the case and additional case-level
characteristics.

# Locations
## The Songer Project
This data will be shared and archived in three key locations. First,
like many of the major NSF-funded judicial politics data collection
projects, we will provide access to the resulting dataset via The Songer
Project. The University of South Carolina's Songer Project (formerly the
Judicial Research Initiative) was established as an electronic archive
of data and research related to the scientific study of law and judicial
politics. It contains and distributes databases including: the six
datasets collected by Harold Spaeth on the U.S. Supreme Court; the U.S.
Courts of Appeals Database collected by Donald Songer; the National High
Courts Database collected by Stacia Haynie, Reginald Sheehan, Donald
Songer, and Neal Tate; and the Attributes of Appeals Court Judges
Database collected by Gary Zuk, Deborah Barrow and Gerard Gryski.

Since its establishment as the S. Sidney Ulmer Project at the University
of Kentucky, and now maintained at the University of South Carolina, the
Songer Project website has received web traffic from individuals in
political science and law, federal judges, and reporters, often with the
intent of downloading the datasets to undertake their own research
projects. We plan to provide the data coming out of this project to this
targeted community through the Songer Project website, distributing the
data files in multiple formats as is customary.

## ICPSR and Harvard Dataverse
Additionally, I plan to archive the data within both ICPSR at the
University of Michigan, where the base IDB dataset is located, and the
social science Dataverse developed by Harvard professor, Gary King. This
will ensure that the data are accessible across both a topic-specific
archive and two wider-reaching repositories. Data will be uploaded to
these three sites within one year of project completion, following the
guidance of the National Science Foundation.





